#include <stdio.h>

#define FILE_ANY_ACCESS                 0
#define METHOD_BUFFERED                 0
#define METHOD_IN_DIRECT                1
#define METHOD_OUT_DIRECT               2
#define METHOD_NEITHER                  3

#define FILE_DEVICE_KEYBOARD            (0x0b)
#define FILE_DEVICE_PHYSICAL_NETCARD    (0x17)


#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)

#define HID_CTL_CODE(id)            CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_NEITHER, FILE_ANY_ACCESS)
#define HID_BUFFER_CTL_CODE(id)     CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_BUFFERED, FILE_ANY_ACCESS)
#define HID_IN_CTL_CODE(id)         CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define HID_OUT_CTL_CODE(id)        CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define IOCTL_HID_GET_DEVICE_DESCRIPTOR             HID_CTL_CODE(0)
#define IOCTL_HID_GET_REPORT_DESCRIPTOR             HID_CTL_CODE(1)
#define IOCTL_HID_READ_REPORT                       HID_CTL_CODE(2)
#define IOCTL_HID_WRITE_REPORT                      HID_CTL_CODE(3)
#define IOCTL_HID_GET_STRING                        HID_CTL_CODE(4)
#define IOCTL_HID_ACTIVATE_DEVICE                   HID_CTL_CODE(7)
#define IOCTL_HID_DEACTIVATE_DEVICE                 HID_CTL_CODE(8)
#define IOCTL_HID_GET_DEVICE_ATTRIBUTES             HID_CTL_CODE(9)
#define IOCTL_HID_SEND_IDLE_NOTIFICATION_REQUEST    HID_CTL_CODE(10)

#define IOCTL_HID_GET_DRIVER_CONFIG             HID_BUFFER_CTL_CODE(100)
#define IOCTL_HID_SET_DRIVER_CONFIG             HID_BUFFER_CTL_CODE(101)
#define IOCTL_HID_GET_POLL_FREQUENCY_MSEC       HID_BUFFER_CTL_CODE(102)
#define IOCTL_HID_SET_POLL_FREQUENCY_MSEC       HID_BUFFER_CTL_CODE(103)
#define IOCTL_GET_NUM_DEVICE_INPUT_BUFFERS      HID_BUFFER_CTL_CODE(104)
#define IOCTL_SET_NUM_DEVICE_INPUT_BUFFERS      HID_BUFFER_CTL_CODE(105)
#define IOCTL_HID_GET_COLLECTION_INFORMATION    HID_BUFFER_CTL_CODE(106)
#define IOCTL_HID_ENABLE_WAKE_ON_SX             HID_BUFFER_CTL_CODE(107)
#define IOCTL_HID_SET_S0_IDLE_TIMEOUT           HID_BUFFER_CTL_CODE(108)


#define IOCTL_HID_GET_COLLECTION_DESCRIPTOR     HID_CTL_CODE(100)
#define IOCTL_HID_FLUSH_QUEUE                   HID_CTL_CODE(101)

#define IOCTL_HID_SET_FEATURE                   HID_IN_CTL_CODE(100)
#define IOCTL_HID_SET_OUTPUT_REPORT             HID_IN_CTL_CODE(101)

#define IOCTL_HID_GET_FEATURE                   HID_OUT_CTL_CODE(100)
#define IOCTL_GET_PHYSICAL_DESCRIPTOR           HID_OUT_CTL_CODE(102)
#define IOCTL_HID_GET_HARDWARE_ID               HID_OUT_CTL_CODE(103)
#define IOCTL_HID_GET_INPUT_REPORT              HID_OUT_CTL_CODE(104)
#define IOCTL_HID_GET_OUTPUT_REPORT             HID_OUT_CTL_CODE(105)

#define IOCTL_HID_GET_MANUFACTURER_STRING       HID_OUT_CTL_CODE(110)
#define IOCTL_HID_GET_PRODUCT_STRING            HID_OUT_CTL_CODE(111)
#define IOCTL_HID_GET_SERIALNUMBER_STRING       HID_OUT_CTL_CODE(112)

#define IOCTL_HID_GET_INDEXED_STRING            HID_OUT_CTL_CODE(120)
#define IOCTL_HID_GET_MS_GENRE_DESCRIPTOR       HID_OUT_CTL_CODE(121)

#define IOCTL_HID_ENABLE_SECURE_READ            HID_CTL_CODE(130)
#define IOCTL_HID_DISABLE_SECURE_READ           HID_CTL_CODE(131)

#define IOCTL_HID_DEVICERESET_NOTIFICATION      HID_CTL_CODE(140)

/*
[x] IOCTL_HID_GET_DEVICE_DESCRIPTOR
[x] IOCTL_HID_GET_REPORT_DESCRIPTOR
[x] IOCTL_HID_GET_DEVICE_ATTRIBUTES
[x] IOCTL_HID_GET_STRING
[x] IOCTL_HID_READ_REPORT
[x] IOCTL_HID_WRITE_REPORT
[ ] IOCTL_HID_GET_INPUT_REPORT
[ ] IOCTL_HID_SET_OUTPUT_REPORT
[ ] IOCTL_HID_GET_FEATURE
[ ] IOCTL_HID_SET_FEATURE
*/

#define _NDIS_CONTROL_CODE(request,method) \
            CTL_CODE(FILE_DEVICE_PHYSICAL_NETCARD, request, method, FILE_ANY_ACCESS)

#define IOCTL_NDIS_QUERY_GLOBAL_STATS   _NDIS_CONTROL_CODE(0, METHOD_OUT_DIRECT)
#define IOCTL_NDIS_QUERY_ALL_STATS      _NDIS_CONTROL_CODE(1, METHOD_OUT_DIRECT)
#define IOCTL_NDIS_DO_PNP_OPERATION     _NDIS_CONTROL_CODE(2, METHOD_BUFFERED)
#define IOCTL_NDIS_QUERY_SELECTED_STATS _NDIS_CONTROL_CODE(3, METHOD_OUT_DIRECT)
#define IOCTL_NDIS_ENUMERATE_INTERFACES _NDIS_CONTROL_CODE(4, METHOD_BUFFERED)
#define IOCTL_NDIS_ADD_TDI_DEVICE       _NDIS_CONTROL_CODE(5, METHOD_BUFFERED)
#define IOCTL_NDIS_GET_LOG_DATA         _NDIS_CONTROL_CODE(7, METHOD_OUT_DIRECT)
#define IOCTL_NDIS_GET_VERSION          _NDIS_CONTROL_CODE(8, METHOD_BUFFERED)


#define WDI_OID_PREFIX 0x0e4400000U
#define WDI_INDICATION_PREFIX 0x40050000U

#define WDI_DEFINE_OID(_messageId)    \
    ((WDI_OID_PREFIX) | ((_messageId)))

#define WDI_DEFINE_INDICATION(_messageId) \
    ((WDI_INDICATION_PREFIX) | ((_messageId)))   

//
// Message IDs
//
#define WDI_TASK_OPEN                                               1
#define WDI_TASK_CLOSE                                              2
#define WDI_SET_HOST_DETECT_ERROR                                   3
#define WDI_TASK_SCAN                                               4
#define WDI_TASK_P2P_DISCOVER                                       5
#define WDI_TASK_CONNECT                                            6
#define WDI_TASK_DOT11_RESET                                        7
#define WDI_TASK_DISCONNECT                                         8
#define WDI_TASK_P2P_SEND_REQUEST_ACTION_FRAME                      9
#define WDI_TASK_P2P_SEND_RESPONSE_ACTION_FRAME                     10
#define WDI_TASK_SET_RADIO_STATE                                    11
#define WDI_TASK_CREATE_PORT                                        12
#define WDI_TASK_DELETE_PORT                                        13
#define WDI_TASK_START_AP                                           14
#define WDI_TASK_STOP_AP                                            15

#define WDI_TASK_SEND_AP_ASSOCIATION_RESPONSE                       17
#define WDI_TASK_SET_READY_TO_RECEIVE_INDICATIONS                   18
#define WDI_SET_POWER_STATE                                         19

#define WDI_INDICATION_DISCONNECT_COMPLETE                          21
#define WDI_INDICATION_SET_RADIO_STATE_COMPLETE                     22
#define WDI_INDICATION_SET_READY_TO_RECEIVE_INDICATIONS_COMPLETE    23
#define WDI_SET_OPERATION_MODE                                      24
#define WDI_SET_P2P_ADDITIONAL_IE                                   25
#define WDI_SET_P2P_LISTEN_STATE                                    26

#define WDI_SET_PRIVACY_EXEMPTION_LIST                              28
#define WDI_SET_ADD_CIPHER_KEYS                                     29
#define WDI_SET_DELETE_CIPHER_KEYS                                  30
#define WDI_SET_DEFAULT_KEY_ID                                      31
#define WDI_SET_CONNECTION_QUALITY                                  32

#define WDI_GET_STATISTICS                                          34

#define WDI_SET_RECEIVE_PACKET_FILTER                               36
#define WDI_GET_ADAPTER_CAPABILITIES                                37

#define WDI_SET_NETWORK_LIST_OFFLOAD                                41

#define WDI_SET_RECEIVE_COALESCING                                  46
#define WDI_GET_BSS_ENTRY_LIST                                      47

#define WDI_INDICATION_DISASSOCIATION                               51
#define WDI_INDICATION_ROAMING_NEEDED                               52
#define WDI_INDICATION_LINK_STATE_CHANGE                            53
#define WDI_INDICATION_P2P_ACTION_FRAME_RECEIVED                    54
#define WDI_INDICATION_AP_ASSOCIATION_REQUEST_RECEIVED              55
#define WDI_INDICATION_NLO_DISCOVERY                                56
#define WDI_INDICATION_WAKE_REASON                                  57
#define WDI_INDICATION_PMKID_CANDIDATE_LIST_UPDATE                  58
#define WDI_INDICATION_TKIP_MIC_FAILURE                             59
#define WDI_INDICATION_SCAN_COMPLETE                                60
#define WDI_INDICATION_P2P_DISCOVERY_COMPLETE                       61
#define WDI_INDICATION_BSS_ENTRY_LIST                               62
#define WDI_INDICATION_DOT11_RESET_COMPLETE                         63
#define WDI_INDICATION_CONNECT_COMPLETE                             64
#define WDI_INDICATION_P2P_SEND_REQUEST_ACTION_FRAME_COMPLETE       65
#define WDI_INDICATION_P2P_SEND_RESPONSE_ACTION_FRAME_COMPLETE      66
#define WDI_INDICATION_RADIO_STATUS                                 67
#define WDI_INDICATION_CREATE_PORT_COMPLETE                         68
#define WDI_INDICATION_DELETE_PORT_COMPLETE                         69
#define WDI_INDICATION_START_AP_COMPLETE                            70
#define WDI_INDICATION_STOP_AP_COMPLETE                             71

#define WDI_INDICATION_SEND_AP_ASSOCIATION_RESPONSE_COMPLETE        73

#define WDI_INDICATION_ASSOCIATION_RESULT                           76
#define WDI_SET_AUTO_POWER_SAVE                                     77
#define WDI_GET_AUTO_POWER_SAVE                                     78
#define WDI_SET_ADD_WOL_PATTERN                                     79
#define WDI_SET_REMOVE_WOL_PATTERN                                  80
#define WDI_SET_MULTICAST_LIST                                      81
#define WDI_SET_ADD_PM_PROTOCOL_OFFLOAD                             82
#define WDI_SET_REMOVE_PM_PROTOCOL_OFFLOAD                          83
#define WDI_INDICATION_P2P_GROUP_OPERATING_CHANNEL                  84
#define WDI_SET_ADAPTER_CONFIGURATION                               85
#define WDI_GET_RECEIVE_COALESCING_MATCH_COUNT                      86
#define WDI_SET_CLEAR_RECEIVE_COALESCING                            87
#define WDI_GET_PM_PROTOCOL_OFFLOAD                                 88
#define WDI_SET_ADVERTISEMENT_INFORMATION                           89
#define WDI_TASK_CHANGE_OPERATION_MODE                              90
#define WDI_INDICATION_CHANGE_OPERATION_MODE_COMPLETE               91
#define WDI_TASK_DELETE_PEER_STATE                                  92
#define WDI_IHV_REQUEST                                             93
#define WDI_INDICATION_IHV_EVENT                                    94
#define WDI_INDICATION_OPEN_COMPLETE                                95
#define WDI_INDICATION_CLOSE_COMPLETE                               96
#define WDI_SET_FLUSH_BSS_ENTRY                                     97
#define WDI_INDICATION_ASSOCIATION_PARAMETERS_REQUEST               98
#define WDI_SET_ASSOCIATION_PARAMETERS                              99
#define WDI_TASK_ROAM                                               100
#define WDI_INDICATION_ROAM_COMPLETE                                101
#define WDI_TASK_SEND_REQUEST_ACTION_FRAME                          102
#define WDI_INDICATION_ACTION_FRAME_RECEIVED                        103
#define WDI_INDICATION_TASK_OFFLOAD_CURRENT_CONFIG                  104
#define WDI_TASK_SEND_RESPONSE_ACTION_FRAME                         105
#define WDI_INDICATION_SEND_REQUEST_ACTION_FRAME_COMPLETE           106
#define WDI_INDICATION_SEND_RESPONSE_ACTION_FRAME_COMPLETE          107
#define WDI_GET_NEXT_ACTION_FRAME_DIALOG_TOKEN                      108
#define WDI_TASK_IHV                                                109
#define WDI_INDICATION_IHV_TASK_REQUEST                             110
#define WDI_INDICATION_IHV_TASK_COMPLETE                            111

#define WDI_INDICATION_STOP_AP                                      115
#define WDI_INDICATION_CAN_SUSTAIN_AP                               116
#define WDI_SET_TCP_OFFLOAD_PARAMETERS                              117
#define WDI_TCP_RSC_STATISTICS                                      118
#define WDI_SET_P2P_START_BACKGROUND_DISCOVERY                      119
#define WDI_SET_P2P_STOP_BACKGROUND_DISCOVERY                       120
#define WDI_INDICATION_FIRMWARE_STALLED                             121
#define WDI_INDICATION_P2P_OPERATING_CHANNEL_ATTRIBUTES             122
#define WDI_SET_P2P_WPS_ENABLED                                     123
#define WDI_SET_ENCAPSULATION_OFFLOAD                               124
#define WDI_SET_END_DWELL_TIME                                      125
#define WDI_INDICATION_FT_ASSOC_PARAMS_NEEDED                       126
#define WDI_SET_FAST_BSS_TRANSITION_PARAMETERS                      127
#define WDI_SET_NEIGHBOR_REPORT_ENTRIES                             128
#define WDI_INDICATION_ADAPTER_STATE                                129
#define WDI_GET_SUPPORTED_DEVICE_SERVICES                           130
#define WDI_DEVICE_SERVICE_COMMAND                                  131
#define WDI_INDICATION_CIPHER_KEY_UPDATED                           132
#define WDI_INDICATION_DEVICE_SERVICE_EVENT                         133
#define WDI_INDICATION_SAE_AUTH_PARAMS_NEEDED                       134
#define WDI_SET_SAE_AUTH_PARAMS                                     135
#define WDI_TASK_REQUEST_FTM                                        136
#define WDI_INDICATION_REQUEST_FTM_COMPLETE                         137

// Special codes
/*++
 Abort task request
 -- */
#define WDI_ABORT_TASK                                              75

#define OID_WDI_TASK_OPEN    \
    WDI_DEFINE_OID(WDI_TASK_OPEN)

#define OID_WDI_TASK_CLOSE    \
    WDI_DEFINE_OID(WDI_TASK_CLOSE)

#define OID_WDI_TASK_SCAN    \
    WDI_DEFINE_OID(WDI_TASK_SCAN)

#define OID_WDI_TASK_P2P_DISCOVER    \
    WDI_DEFINE_OID(WDI_TASK_P2P_DISCOVER)

#define OID_WDI_TASK_CONNECT    \
    WDI_DEFINE_OID(WDI_TASK_CONNECT)

#define OID_WDI_TASK_DOT11_RESET    \
    WDI_DEFINE_OID(WDI_TASK_DOT11_RESET)

#define OID_WDI_TASK_DISCONNECT    \
    WDI_DEFINE_OID(WDI_TASK_DISCONNECT)

#define OID_WDI_TASK_P2P_SEND_REQUEST_ACTION_FRAME    \
    WDI_DEFINE_OID(WDI_TASK_P2P_SEND_REQUEST_ACTION_FRAME)

#define OID_WDI_TASK_P2P_SEND_RESPONSE_ACTION_FRAME    \
    WDI_DEFINE_OID(WDI_TASK_P2P_SEND_RESPONSE_ACTION_FRAME)

#define OID_WDI_TASK_SET_RADIO_STATE    \
    WDI_DEFINE_OID(WDI_TASK_SET_RADIO_STATE)

#define OID_WDI_TASK_CREATE_PORT    \
    WDI_DEFINE_OID(WDI_TASK_CREATE_PORT)

#define OID_WDI_TASK_DELETE_PORT    \
    WDI_DEFINE_OID(WDI_TASK_DELETE_PORT)

#define OID_WDI_TASK_START_AP    \
    WDI_DEFINE_OID(WDI_TASK_START_AP)

#define OID_WDI_TASK_STOP_AP    \
    WDI_DEFINE_OID(WDI_TASK_STOP_AP)

#define OID_WDI_TASK_SEND_AP_ASSOCIATION_RESPONSE    \
    WDI_DEFINE_OID(WDI_TASK_SEND_AP_ASSOCIATION_RESPONSE)

#define OID_WDI_SET_POWER_STATE    \
    WDI_DEFINE_OID(WDI_SET_POWER_STATE)

#define OID_WDI_SET_OPERATION_MODE    \
    WDI_DEFINE_OID(WDI_SET_OPERATION_MODE)

#define OID_WDI_SET_P2P_ADDITIONAL_IE    \
    WDI_DEFINE_OID(WDI_SET_P2P_ADDITIONAL_IE)

#define OID_WDI_SET_P2P_LISTEN_STATE    \
    WDI_DEFINE_OID(WDI_SET_P2P_LISTEN_STATE)

#define OID_WDI_SET_PRIVACY_EXEMPTION_LIST    \
    WDI_DEFINE_OID(WDI_SET_PRIVACY_EXEMPTION_LIST)

#define OID_WDI_SET_ADD_CIPHER_KEYS    \
    WDI_DEFINE_OID(WDI_SET_ADD_CIPHER_KEYS)

#define OID_WDI_SET_DELETE_CIPHER_KEYS    \
    WDI_DEFINE_OID(WDI_SET_DELETE_CIPHER_KEYS)

#define OID_WDI_SET_DEFAULT_KEY_ID    \
    WDI_DEFINE_OID(WDI_SET_DEFAULT_KEY_ID)

#define OID_WDI_SET_CONNECTION_QUALITY    \
    WDI_DEFINE_OID(WDI_SET_CONNECTION_QUALITY)

#define OID_WDI_GET_STATISTICS    \
    WDI_DEFINE_OID(WDI_GET_STATISTICS)

#define OID_WDI_SET_RECEIVE_PACKET_FILTER    \
    WDI_DEFINE_OID(WDI_SET_RECEIVE_PACKET_FILTER)

#define OID_WDI_GET_ADAPTER_CAPABILITIES    \
    WDI_DEFINE_OID(WDI_GET_ADAPTER_CAPABILITIES)

#define OID_WDI_SET_NETWORK_LIST_OFFLOAD    \
    WDI_DEFINE_OID(WDI_SET_NETWORK_LIST_OFFLOAD)

#define OID_WDI_SET_RECEIVE_COALESCING    \
    WDI_DEFINE_OID(WDI_SET_RECEIVE_COALESCING)

#define OID_WDI_GET_BSS_ENTRY_LIST    \
    WDI_DEFINE_OID(WDI_GET_BSS_ENTRY_LIST)

#define OID_WDI_SET_AUTO_POWER_SAVE    \
    WDI_DEFINE_OID(WDI_SET_AUTO_POWER_SAVE)

#define OID_WDI_GET_AUTO_POWER_SAVE    \
    WDI_DEFINE_OID(WDI_GET_AUTO_POWER_SAVE)

#define OID_WDI_SET_ADD_WOL_PATTERN    \
    WDI_DEFINE_OID(WDI_SET_ADD_WOL_PATTERN)

#define OID_WDI_SET_REMOVE_WOL_PATTERN    \
    WDI_DEFINE_OID(WDI_SET_REMOVE_WOL_PATTERN)

#define OID_WDI_SET_MULTICAST_LIST    \
    WDI_DEFINE_OID(WDI_SET_MULTICAST_LIST)

#define OID_WDI_SET_ADD_PM_PROTOCOL_OFFLOAD    \
    WDI_DEFINE_OID(WDI_SET_ADD_PM_PROTOCOL_OFFLOAD)

#define OID_WDI_SET_REMOVE_PM_PROTOCOL_OFFLOAD    \
    WDI_DEFINE_OID(WDI_SET_REMOVE_PM_PROTOCOL_OFFLOAD)

#define OID_WDI_SET_ADAPTER_CONFIGURATION    \
    WDI_DEFINE_OID(WDI_SET_ADAPTER_CONFIGURATION)

#define OID_WDI_GET_RECEIVE_COALESCING_MATCH_COUNT    \
    WDI_DEFINE_OID(WDI_GET_RECEIVE_COALESCING_MATCH_COUNT)

#define OID_WDI_SET_CLEAR_RECEIVE_COALESCING    \
    WDI_DEFINE_OID(WDI_SET_CLEAR_RECEIVE_COALESCING)

#define OID_WDI_GET_PM_PROTOCOL_OFFLOAD    \
    WDI_DEFINE_OID(WDI_GET_PM_PROTOCOL_OFFLOAD)

#define OID_WDI_SET_ADVERTISEMENT_INFORMATION    \
    WDI_DEFINE_OID(WDI_SET_ADVERTISEMENT_INFORMATION)

#define OID_WDI_TASK_CHANGE_OPERATION_MODE    \
    WDI_DEFINE_OID(WDI_TASK_CHANGE_OPERATION_MODE)

#define OID_WDI_TASK_DELETE_PEER_STATE    \
    WDI_DEFINE_OID(WDI_TASK_DELETE_PEER_STATE)

#define OID_WDI_IHV_REQUEST    \
    WDI_DEFINE_OID(WDI_IHV_REQUEST)

#define OID_WDI_TASK_ROAM    \
    WDI_DEFINE_OID(WDI_TASK_ROAM)

#define OID_WDI_SET_FLUSH_BSS_ENTRY    \
    WDI_DEFINE_OID(WDI_SET_FLUSH_BSS_ENTRY)

#define OID_WDI_SET_ASSOCIATION_PARAMETERS    \
    WDI_DEFINE_OID(WDI_SET_ASSOCIATION_PARAMETERS)

#define OID_WDI_GET_NEXT_ACTION_FRAME_DIALOG_TOKEN    \
    WDI_DEFINE_OID(WDI_GET_NEXT_ACTION_FRAME_DIALOG_TOKEN)

#define OID_WDI_TASK_SEND_REQUEST_ACTION_FRAME    \
    WDI_DEFINE_OID(WDI_TASK_SEND_REQUEST_ACTION_FRAME)

#define OID_WDI_TASK_SEND_RESPONSE_ACTION_FRAME    \
    WDI_DEFINE_OID(WDI_TASK_SEND_RESPONSE_ACTION_FRAME)

#define OID_WDI_SET_TCP_OFFLOAD_PARAMETERS    \
    WDI_DEFINE_OID(WDI_SET_TCP_OFFLOAD_PARAMETERS)

#define OID_WDI_TCP_RSC_STATISTICS    \
    WDI_DEFINE_OID(WDI_TCP_RSC_STATISTICS)

#define OID_WDI_SET_P2P_WPS_ENABLED \
    WDI_DEFINE_OID(WDI_SET_P2P_WPS_ENABLED)

#define OID_WDI_SET_P2P_START_BACKGROUND_DISCOVERY \
    WDI_DEFINE_OID(WDI_SET_P2P_START_BACKGROUND_DISCOVERY)

#define OID_WDI_SET_P2P_STOP_BACKGROUND_DISCOVERY \
    WDI_DEFINE_OID(WDI_SET_P2P_STOP_BACKGROUND_DISCOVERY)

#define OID_WDI_TASK_IHV \
    WDI_DEFINE_OID(WDI_TASK_IHV)

#define OID_WDI_SET_ENCAPSULATION_OFFLOAD \
    WDI_DEFINE_OID(WDI_SET_ENCAPSULATION_OFFLOAD)

#define OID_WDI_SET_END_DWELL_TIME \
    WDI_DEFINE_OID(WDI_SET_END_DWELL_TIME)
 
#define OID_WDI_SET_FAST_BSS_TRANSITION_PARAMETERS \
    WDI_DEFINE_OID(WDI_SET_FAST_BSS_TRANSITION_PARAMETERS)

#define OID_WDI_SET_NEIGHBOR_REPORT_ENTRIES \
    WDI_DEFINE_OID(WDI_SET_NEIGHBOR_REPORT_ENTRIES)

#define OID_WDI_GET_SUPPORTED_DEVICE_SERVICES \
    WDI_DEFINE_OID(WDI_GET_SUPPORTED_DEVICE_SERVICES)

#define OID_WDI_DEVICE_SERVICE_COMMAND \
    WDI_DEFINE_OID(WDI_DEVICE_SERVICE_COMMAND)

#define OID_WDI_SET_SAE_AUTH_PARAMS \
    WDI_DEFINE_OID(WDI_SET_SAE_AUTH_PARAMS)

#define OID_WDI_TASK_REQUEST_FTM \
    WDI_DEFINE_OID(WDI_TASK_REQUEST_FTM)

#define NDIS_STATUS_WDI_INDICATION_DISCONNECT_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_DISCONNECT_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_SET_RADIO_STATE_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_SET_RADIO_STATE_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_DISASSOCIATION    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_DISASSOCIATION)

#define NDIS_STATUS_WDI_INDICATION_ROAMING_NEEDED    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_ROAMING_NEEDED)

#define NDIS_STATUS_WDI_INDICATION_LINK_STATE_CHANGE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_LINK_STATE_CHANGE)

#define NDIS_STATUS_WDI_INDICATION_P2P_ACTION_FRAME_RECEIVED    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_P2P_ACTION_FRAME_RECEIVED)

#define NDIS_STATUS_WDI_INDICATION_AP_ASSOCIATION_REQUEST_RECEIVED    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_AP_ASSOCIATION_REQUEST_RECEIVED)

#define NDIS_STATUS_WDI_INDICATION_NLO_DISCOVERY   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_NLO_DISCOVERY)

#define NDIS_STATUS_WDI_INDICATION_WAKE_REASON    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_WAKE_REASON)

#define NDIS_STATUS_WDI_INDICATION_PMKID_CANDIDATE_LIST_UPDATE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_PMKID_CANDIDATE_LIST_UPDATE)

#define NDIS_STATUS_WDI_INDICATION_TKIP_MIC_FAILURE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_TKIP_MIC_FAILURE)

#define NDIS_STATUS_WDI_INDICATION_ACTION_FRAME_RECEIVED    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_ACTION_FRAME_RECEIVED)

#define NDIS_STATUS_WDI_INDICATION_SEND_REQUEST_ACTION_FRAME_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_SEND_REQUEST_ACTION_FRAME_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_SEND_RESPONSE_ACTION_FRAME_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_SEND_RESPONSE_ACTION_FRAME_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_SCAN_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_SCAN_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_P2P_DISCOVERY_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_P2P_DISCOVERY_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_BSS_ENTRY_LIST    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_BSS_ENTRY_LIST)

#define NDIS_STATUS_WDI_INDICATION_DOT11_RESET_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_DOT11_RESET_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_CONNECT_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_CONNECT_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_P2P_SEND_REQUEST_ACTION_FRAME_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_P2P_SEND_REQUEST_ACTION_FRAME_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_P2P_SEND_RESPONSE_ACTION_FRAME_COMPLETE    \
    WDI_DEFINE_INDICATION(WDI_INDICATION_P2P_SEND_RESPONSE_ACTION_FRAME_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_RADIO_STATUS   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_RADIO_STATUS)

#define NDIS_STATUS_WDI_INDICATION_CREATE_PORT_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_CREATE_PORT_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_DELETE_PORT_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_DELETE_PORT_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_START_AP_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_START_AP_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_STOP_AP_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_STOP_AP_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_STOP_AP   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_STOP_AP)

#define NDIS_STATUS_WDI_INDICATION_CAN_SUSTAIN_AP   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_CAN_SUSTAIN_AP)

#define NDIS_STATUS_WDI_INDICATION_SEND_AP_ASSOCIATION_RESPONSE_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_SEND_AP_ASSOCIATION_RESPONSE_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_ASSOCIATION_RESULT   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_ASSOCIATION_RESULT)

#define NDIS_STATUS_WDI_INDICATION_P2P_GROUP_OPERATING_CHANNEL   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_P2P_GROUP_OPERATING_CHANNEL)

#define NDIS_STATUS_WDI_INDICATION_CHANGE_OPERATION_MODE_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_CHANGE_OPERATION_MODE_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_IHV_EVENT   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_IHV_EVENT)

#define NDIS_STATUS_WDI_INDICATION_OPEN_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_OPEN_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_CLOSE_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_CLOSE_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_ROAM_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_ROAM_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_ASSOCIATION_PARAMETERS_REQUEST   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_ASSOCIATION_PARAMETERS_REQUEST)

#define NDIS_STATUS_WDI_INDICATION_TASK_OFFLOAD_CURRENT_CONFIG   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_TASK_OFFLOAD_CURRENT_CONFIG)

#define NDIS_STATUS_WDI_TCP_RSC_STATISTICS   \
    WDI_DEFINE_INDICATION(WDI_TCP_RSC_STATISTICS)

#define NDIS_STATUS_WDI_INDICATION_P2P_OPERATING_CHANNEL_ATTRIBUTES   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_P2P_OPERATING_CHANNEL_ATTRIBUTES)

#define NDIS_STATUS_WDI_INDICATION_IHV_TASK_REQUEST   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_IHV_TASK_REQUEST)

#define NDIS_STATUS_WDI_INDICATION_IHV_TASK_COMPLETE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_IHV_TASK_COMPLETE)

#define NDIS_STATUS_WDI_INDICATION_FIRMWARE_STALLED \
    WDI_DEFINE_INDICATION(WDI_INDICATION_FIRMWARE_STALLED)

#define NDIS_STATUS_WDI_INDICATION_FT_ASSOC_PARAMS_NEEDED \
    WDI_DEFINE_INDICATION(WDI_INDICATION_FT_ASSOC_PARAMS_NEEDED)

#define NDIS_STATUS_WDI_INDICATION_ADAPTER_STATE   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_ADAPTER_STATE)

#define NDIS_STATUS_WDI_INDICATION_CIPHER_KEY_UPDATED   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_CIPHER_KEY_UPDATED)

#define NDIS_STATUS_WDI_INDICATION_DEVICE_SERVICE_EVENT   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_DEVICE_SERVICE_EVENT)

#define NDIS_STATUS_WDI_INDICATION_SAE_AUTH_PARAMS_NEEDED   \
    WDI_DEFINE_INDICATION(WDI_INDICATION_SAE_AUTH_PARAMS_NEEDED)

#define NDIS_STATUS_WDI_INDICATION_REQUEST_FTM_COMPLETE \
    WDI_DEFINE_INDICATION(WDI_INDICATION_REQUEST_FTM_COMPLETE)


int main()
{
    printf("OID_WDI_SET_POWER_STATE %x\n", OID_WDI_SET_POWER_STATE);
    printf("QUERY GLOBAL STATS %x\n", IOCTL_NDIS_QUERY_GLOBAL_STATS);
#if 0
    printf("%x\n", IOCTL_HID_GET_DEVICE_DESCRIPTOR);
    printf("%x\n", IOCTL_HID_GET_REPORT_DESCRIPTOR);
    printf("%x\n", IOCTL_HID_READ_REPORT);
    printf("%x\n", IOCTL_HID_WRITE_REPORT);
    printf("%x\n", IOCTL_HID_GET_STRING);
    printf("%x\n", IOCTL_HID_ACTIVATE_DEVICE);
    printf("%x\n", IOCTL_HID_DEACTIVATE_DEVICE);
    printf("%x\n", IOCTL_HID_GET_DEVICE_ATTRIBUTES);
    printf("%x\n", IOCTL_HID_SEND_IDLE_NOTIFICATION_REQUEST);
    printf("%x\n", IOCTL_HID_GET_INPUT_REPORT);
    printf("%x\n", IOCTL_HID_SET_OUTPUT_REPORT);
    printf("%x\n", IOCTL_HID_GET_FEATURE);
    printf("%x\n", IOCTL_HID_SET_FEATURE);
#endif
}

