#include <stdio.h>

#define FILE_ANY_ACCESS                 0
#define METHOD_BUFFERED                 0
#define METHOD_IN_DIRECT                1
#define METHOD_OUT_DIRECT               2
#define METHOD_NEITHER                  3

#define FILE_DEVICE_KEYBOARD            (0xb)


#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
    ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
)

#define HID_CTL_CODE(id)            CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_NEITHER, FILE_ANY_ACCESS)
#define HID_BUFFER_CTL_CODE(id)     CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_BUFFERED, FILE_ANY_ACCESS)
#define HID_IN_CTL_CODE(id)         CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define HID_OUT_CTL_CODE(id)        CTL_CODE(FILE_DEVICE_KEYBOARD, (id), METHOD_OUT_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_HID_GET_DEVICE_DESCRIPTOR             HID_CTL_CODE(0)
#define IOCTL_HID_GET_REPORT_DESCRIPTOR             HID_CTL_CODE(1)
#define IOCTL_HID_READ_REPORT                       HID_CTL_CODE(2)
#define IOCTL_HID_WRITE_REPORT                      HID_CTL_CODE(3)
#define IOCTL_HID_GET_STRING                        HID_CTL_CODE(4)
#define IOCTL_HID_ACTIVATE_DEVICE                   HID_CTL_CODE(7)
#define IOCTL_HID_DEACTIVATE_DEVICE                 HID_CTL_CODE(8)
#define IOCTL_HID_GET_DEVICE_ATTRIBUTES             HID_CTL_CODE(9)
#define IOCTL_HID_SEND_IDLE_NOTIFICATION_REQUEST    HID_CTL_CODE(10)

#define IOCTL_HID_GET_DRIVER_CONFIG             HID_BUFFER_CTL_CODE(100)
#define IOCTL_HID_SET_DRIVER_CONFIG             HID_BUFFER_CTL_CODE(101)
#define IOCTL_HID_GET_POLL_FREQUENCY_MSEC       HID_BUFFER_CTL_CODE(102)
#define IOCTL_HID_SET_POLL_FREQUENCY_MSEC       HID_BUFFER_CTL_CODE(103)
#define IOCTL_GET_NUM_DEVICE_INPUT_BUFFERS      HID_BUFFER_CTL_CODE(104)
#define IOCTL_SET_NUM_DEVICE_INPUT_BUFFERS      HID_BUFFER_CTL_CODE(105)
#define IOCTL_HID_GET_COLLECTION_INFORMATION    HID_BUFFER_CTL_CODE(106)
#define IOCTL_HID_ENABLE_WAKE_ON_SX             HID_BUFFER_CTL_CODE(107)
#define IOCTL_HID_SET_S0_IDLE_TIMEOUT           HID_BUFFER_CTL_CODE(108)


#define IOCTL_HID_GET_COLLECTION_DESCRIPTOR     HID_CTL_CODE(100)
#define IOCTL_HID_FLUSH_QUEUE                   HID_CTL_CODE(101)

#define IOCTL_HID_SET_FEATURE                   HID_IN_CTL_CODE(100)
#define IOCTL_HID_SET_OUTPUT_REPORT             HID_IN_CTL_CODE(101)

#define IOCTL_HID_GET_FEATURE                   HID_OUT_CTL_CODE(100)
#define IOCTL_GET_PHYSICAL_DESCRIPTOR           HID_OUT_CTL_CODE(102)
#define IOCTL_HID_GET_HARDWARE_ID               HID_OUT_CTL_CODE(103)
#define IOCTL_HID_GET_INPUT_REPORT              HID_OUT_CTL_CODE(104)
#define IOCTL_HID_GET_OUTPUT_REPORT             HID_OUT_CTL_CODE(105)

#define IOCTL_HID_GET_MANUFACTURER_STRING       HID_OUT_CTL_CODE(110)
#define IOCTL_HID_GET_PRODUCT_STRING            HID_OUT_CTL_CODE(111)
#define IOCTL_HID_GET_SERIALNUMBER_STRING       HID_OUT_CTL_CODE(112)

#define IOCTL_HID_GET_INDEXED_STRING            HID_OUT_CTL_CODE(120)
#define IOCTL_HID_GET_MS_GENRE_DESCRIPTOR       HID_OUT_CTL_CODE(121)

#define IOCTL_HID_ENABLE_SECURE_READ            HID_CTL_CODE(130)
#define IOCTL_HID_DISABLE_SECURE_READ           HID_CTL_CODE(131)

#define IOCTL_HID_DEVICERESET_NOTIFICATION      HID_CTL_CODE(140)

/*
[x] IOCTL_HID_GET_DEVICE_DESCRIPTOR
[x] IOCTL_HID_GET_REPORT_DESCRIPTOR
[x] IOCTL_HID_GET_DEVICE_ATTRIBUTES
[x] IOCTL_HID_GET_STRING
[x] IOCTL_HID_READ_REPORT
[x] IOCTL_HID_WRITE_REPORT
[ ] IOCTL_HID_GET_INPUT_REPORT
[ ] IOCTL_HID_SET_OUTPUT_REPORT
[ ] IOCTL_HID_GET_FEATURE
[ ] IOCTL_HID_SET_FEATURE
*/


int main()
{
    printf("%x\n", IOCTL_HID_GET_DEVICE_DESCRIPTOR);
    printf("%x\n", IOCTL_HID_GET_REPORT_DESCRIPTOR);
    printf("%x\n", IOCTL_HID_READ_REPORT);
    printf("%x\n", IOCTL_HID_WRITE_REPORT);
    printf("%x\n", IOCTL_HID_GET_STRING);
    printf("%x\n", IOCTL_HID_ACTIVATE_DEVICE);
    printf("%x\n", IOCTL_HID_DEACTIVATE_DEVICE);
    printf("%x\n", IOCTL_HID_GET_DEVICE_ATTRIBUTES);
    printf("%x\n", IOCTL_HID_SEND_IDLE_NOTIFICATION_REQUEST);
    printf("%x\n", IOCTL_HID_GET_INPUT_REPORT);
    printf("%x\n", IOCTL_HID_SET_OUTPUT_REPORT);
    printf("%x\n", IOCTL_HID_GET_FEATURE);
    printf("%x\n", IOCTL_HID_SET_FEATURE);
}

